//---------------------------------------------------------------------------
#include <vcl.h>
#pragma hdrstop
#include "Unit1.h"
#include "Unit3.h"
#include "Unit7.h"


void TSellos::CrearSellos (int ano, int mes)
{
TS *S;
S= new TS;
Kines= mes*28 + ano * 365 + 104;
Kines-=INT(Kines/20) *20 ;

if (Form1->ComboBox2->ItemIndex ==13){
    Form1->Image1->Picture->LoadFromFile(S->Sello(Kines));
    Form1->Image2->Picture->LoadFromFile("nada.bmp");
    Form1->Image3->Picture= Form1->Image2->Picture;
    Form1->Image4->Picture= Form1->Image2->Picture;
    Form1->Image5->Picture= Form1->Image2->Picture;
    Form1->Image6->Picture= Form1->Image2->Picture;
    Form1->Image7->Picture= Form1->Image2->Picture;
    Form1->Image8->Picture= Form1->Image2->Picture;
    Form1->Image9->Picture= Form1->Image2->Picture;
    Form1->Image10->Picture= Form1->Image2->Picture;
    Form1->Image11->Picture= Form1->Image2->Picture;
    Form1->Image12->Picture= Form1->Image2->Picture;
    Form1->Image13->Picture= Form1->Image2->Picture;
    Form1->Image14->Picture= Form1->Image2->Picture;
    Form1->Image15->Picture= Form1->Image2->Picture;
    Form1->Image16->Picture= Form1->Image2->Picture;
    Form1->Image17->Picture= Form1->Image2->Picture;
    Form1->Image18->Picture= Form1->Image2->Picture;
    Form1->Image19->Picture= Form1->Image2->Picture;
    Form1->Image20->Picture= Form1->Image2->Picture;
    Form1->Image21->Picture= Form1->Image2->Picture;
    Form1->Image22->Picture= Form1->Image2->Picture;
    Form1->Image23->Picture= Form1->Image2->Picture;
    Form1->Image24->Picture= Form1->Image2->Picture;
    Form1->Image25->Picture= Form1->Image2->Picture;
    Form1->Image26->Picture= Form1->Image2->Picture;
    Form1->Image27->Picture= Form1->Image2->Picture;
    Form1->Image28->Picture= Form1->Image2->Picture;
     }
else {
Form1->Image1->Picture->LoadFromFile(S->Sello(Kines));
Form1->Image2->Picture->LoadFromFile(S->Sello(Kines+1));
Form1->Image3->Picture->LoadFromFile(S->Sello(Kines + 2));
Form1->Image4->Picture->LoadFromFile(S->Sello(Kines + 3));
Form1->Image5->Picture->LoadFromFile(S->Sello(Kines + 4));
Form1->Image6->Picture->LoadFromFile(S->Sello(Kines + 5));
Form1->Image7->Picture->LoadFromFile(S->Sello(Kines + 6));
Form1->Image8->Picture->LoadFromFile(S->Sello(Kines + 7));
Form1->Image9->Picture->LoadFromFile(S->Sello(Kines + 8));
Form1->Image10->Picture->LoadFromFile(S->Sello(Kines + 9));
Form1->Image11->Picture->LoadFromFile(S->Sello(Kines + 10));
Form1->Image12->Picture->LoadFromFile(S->Sello(Kines + 11));
Form1->Image13->Picture->LoadFromFile(S->Sello(Kines + 12));
Form1->Image14->Picture->LoadFromFile(S->Sello(Kines + 13));
Form1->Image15->Picture->LoadFromFile(S->Sello(Kines + 14));
Form1->Image16->Picture->LoadFromFile(S->Sello(Kines + 15));
Form1->Image17->Picture->LoadFromFile(S->Sello(Kines + 16));
Form1->Image18->Picture->LoadFromFile(S->Sello(Kines + 17));
Form1->Image19->Picture->LoadFromFile(S->Sello(Kines + 18));
Form1->Image20->Picture->LoadFromFile(S->Sello(Kines + 19));
Form1->Image21->Picture= Form1->Image1->Picture;
Form1->Image22->Picture= Form1->Image2->Picture;
Form1->Image23->Picture= Form1->Image3->Picture;
Form1->Image24->Picture= Form1->Image4->Picture;
Form1->Image25->Picture= Form1->Image5->Picture;
Form1->Image26->Picture= Form1->Image6->Picture;
Form1->Image27->Picture= Form1->Image7->Picture;
Form1->Image28->Picture= Form1->Image8->Picture;
   }

 switch (Form1->ComboBox2->ItemIndex)
 {
 case 0: Form1->Label16->Caption= "SERVICIO PLANETARIO: Identificar el Propósito: ¿Cuál es mi meta?";
          break;
 case 1: Form1->Label16->Caption= "SERVICIO PLANETARIO: Identificar el Desafío: ¿Cuáles son los obstáculos?";
          break;
 case 2: Form1->Label16->Caption= "SERVICIO PLANETARIO: Identificar el Servicio: ¿Cómo puedo dar un mejor servicio?";
          break;
 case 3: Form1->Label16->Caption= "SERVICIO PLANETARIO: Identificar la Forma: ¿Cuál es la forma que me sincroniza?";
          break;
 case 4: Form1->Label16->Caption= "SERVICIO PLANETARIO: Tomar el Comando: ¿Cómo puedo reunir los recursos y tomar el comando de mi propia autoridad?";
          break;
 case 5: Form1->Label16->Caption= "SERVICIO PLANETARIO: Igualdad del Desafío: ¿Cómo organizo para equilibrarme?";
          break;
 case 6: Form1->Label16->Caption= "SERVICIO PLANETARIO: Armonización del Servicio: ¿Cómo sintonizo el servicio con la acción?";
          break;
 case 7: Form1->Label16->Caption= "SERVICIO PLANETARIO: Integridad de la Forma: ¿Vivo lo que creo?";
          break;
 case 8: Form1->Label16->Caption= "SERVICIO PLANETARIO: Formalizar la Acción: ¿Cómo logro mi meta?";
          break;
 case 9: Form1->Label16->Caption= "SERVICIO PLANETARIO: Manifestación del Desafío: ¿Cómo puedo mejorar lo que hago?";
          break;
 case 10: Form1->Label16->Caption= "SERVICIO PLANETARIO: Liberación del Servicio: ¿Cómo puedo liberarme y dejarme ir?";
          break;
 case 11: Form1->Label16->Caption= "SERVICIO PLANETARIO: Cooperación de la Forma: ¿Cómo puedo dedicar mi ser a todo lo que posee vida?";
          break;
 case 12: Form1->Label16->Caption= "SERVICIO PLANETARIO: Tomar del Vuelco Mágico: ¿Comó puedo Expandir mi Alegría y mi Amor?";
          break;
  }
Form1->Label19->Caption = IntToStr(Form1->ComboBox2->ItemIndex + 1);

 delete S;
 }

void TSellos::CrearTodo (int d, int s)
{
Form1->Label20->Caption= IntToStr(s);
Kin= (Form1->ComboBox2->ItemIndex*4+ s)*7 + 96 + d + (Form1->ComboBox1->ItemIndex * 365);
while (Kin>260) Kin-=260;
Form1->Label3->Caption= "KIN " + FloatToStr(Kin);

//Coloco todas las Imganes en el mismo Tamaño
 Form1->Image1->Width= 57;
 Form1->Image1->Height= 57;
 Form1->Image2->Width= 57;
 Form1->Image2->Height= 57;
 Form1->Image3->Width= 57;
 Form1->Image3->Height= 57;
 Form1->Image4->Width= 57;
 Form1->Image4->Height= 57;
 Form1->Image5->Width= 57;
 Form1->Image5->Height= 57;
 Form1->Image6->Width= 57;
 Form1->Image6->Height= 57;
 Form1->Image7->Width= 57;
 Form1->Image7->Height= 57;
 Form1->Image8->Width= 57;
 Form1->Image8->Height= 57;
 Form1->Image9->Width= 57;
 Form1->Image9->Height= 57;
 Form1->Image10->Width= 57;
 Form1->Image10->Height= 57;
 Form1->Image11->Width= 57;
 Form1->Image11->Height= 57;
 Form1->Image12->Width= 57;
 Form1->Image12->Height= 57;
 Form1->Image13->Width= 57;
 Form1->Image13->Height= 57;
 Form1->Image14->Width= 57;
 Form1->Image14->Height= 57;
 Form1->Image15->Width= 57;
 Form1->Image15->Height= 57;
 Form1->Image16->Width= 57;
 Form1->Image16->Height= 57;
 Form1->Image17->Width= 57;
 Form1->Image17->Height= 57;
 Form1->Image18->Width= 57;
 Form1->Image18->Height= 57;
 Form1->Image19->Width= 57;
 Form1->Image19->Height= 57;
 Form1->Image20->Width= 57;
 Form1->Image20->Height= 57;
 Form1->Image21->Width= 57;
 Form1->Image21->Height= 57;
 Form1->Image22->Width= 57;
 Form1->Image22->Height= 57;
 Form1->Image23->Width= 57;
 Form1->Image23->Height= 57;
 Form1->Image24->Width= 57;
 Form1->Image24->Height= 57;
 Form1->Image25->Width= 57;
 Form1->Image25->Height= 57;
 Form1->Image26->Width= 57;
 Form1->Image26->Height= 57;
 Form1->Image27->Width= 57;
 Form1->Image27->Height= 57;
 Form1->Image28->Width= 57;
 Form1->Image28->Height= 57;
Tono= Kin - (INT(Kin / 13) *13);
switch (s*7+d)
     {
      case 8:  Form1->Image1->Width= 65;
               Form1->Image1->Height= 65;
               Form1->Image29->Picture= Form1->Image1->Picture;
               Form1->Image39->Picture->LoadFromFile ("Runa 1.bmp");
               Form1->Label2->Caption= "Plasma 1";
               Form1->Label18->Caption= "Plasma de Cristo";
               Form1->Image57->Picture->LoadFromFile("Septimo.bmp");
               switch (Tono){
                  case 0: Form1->Image30->Picture= Form1->Image5->Picture; break;
                  case 1: Form1->Image30->Picture= Form1->Image1->Picture; break;
                  case 2: Form1->Image30->Picture= Form1->Image13->Picture; break;
                  case 3: Form1->Image30->Picture= Form1->Image5->Picture; break;
                  case 4: Form1->Image30->Picture= Form1->Image17->Picture; break;
                  case 5: Form1->Image30->Picture= Form1->Image9->Picture; break;
                  case 6: Form1->Image30->Picture= Form1->Image1->Picture; break;
                  case 7: Form1->Image30->Picture= Form1->Image13->Picture; break;
                  case 8: Form1->Image30->Picture= Form1->Image5->Picture; break;
                  case 9: Form1->Image30->Picture= Form1->Image17->Picture; break;
                  case 10: Form1->Image30->Picture= Form1->Image9->Picture; break;
                  case 11: Form1->Image30->Picture= Form1->Image1->Picture; break;
                  case 12: Form1->Image30->Picture= Form1->Image13->Picture; break;
                 }
               break;
      case 9:  Form1->Image2->Width= 65;
               Form1->Image2->Height= 65;
               Form1->Image29->Picture= Form1->Image2->Picture;
               Form1->Image39->Picture->LoadFromFile ("Runa 2.bmp");
               Form1->Label2->Caption= "Plasma 2";
               Form1->Label18->Caption= "Plasma de Mahoma";
               Form1->Image57->Picture->LoadFromFile("Primero.bmp");
               switch (Tono){
                  case 0: Form1->Image30->Picture= Form1->Image6->Picture; break;
                  case 1: Form1->Image30->Picture= Form1->Image2->Picture; break;
                  case 2: Form1->Image30->Picture= Form1->Image14->Picture; break;
                  case 3: Form1->Image30->Picture= Form1->Image6->Picture; break;
                  case 4: Form1->Image30->Picture= Form1->Image18->Picture; break;
                  case 5: Form1->Image30->Picture= Form1->Image10->Picture; break;
                  case 6: Form1->Image30->Picture= Form1->Image2->Picture; break;
                  case 7: Form1->Image30->Picture= Form1->Image14->Picture; break;
                  case 8: Form1->Image30->Picture= Form1->Image6->Picture; break;
                  case 9: Form1->Image30->Picture= Form1->Image18->Picture; break;
                  case 10: Form1->Image30->Picture= Form1->Image10->Picture; break;
                  case 11: Form1->Image30->Picture= Form1->Image2->Picture; break;
                  case 12: Form1->Image30->Picture= Form1->Image14->Picture; break;
                  }
               break;
      case 10: Form1->Image3->Width= 65;
               Form1->Image3->Height= 65;
               Form1->Image29->Picture= Form1->Image3->Picture;
               Form1->Image39->Picture->LoadFromFile ("Runa 3.bmp");
               Form1->Label2->Caption= "Plasma 3";
               Form1->Label18->Caption= "Plasma de Pacal Votan";
               Form1->Image57->Picture->LoadFromFile("Sexto.bmp");
               switch (Tono){
                  case 0: Form1->Image30->Picture= Form1->Image7->Picture; break;
                  case 1: Form1->Image30->Picture= Form1->Image3->Picture; break;
                  case 2: Form1->Image30->Picture= Form1->Image15->Picture; break;
                  case 3: Form1->Image30->Picture= Form1->Image7->Picture; break;
                  case 4: Form1->Image30->Picture= Form1->Image19->Picture; break;
                  case 5: Form1->Image30->Picture= Form1->Image11->Picture; break;
                  case 6: Form1->Image30->Picture= Form1->Image3->Picture; break;
                  case 7: Form1->Image30->Picture= Form1->Image15->Picture; break;
                  case 8: Form1->Image30->Picture= Form1->Image7->Picture; break;
                  case 9: Form1->Image30->Picture= Form1->Image19->Picture; break;
                  case 10: Form1->Image30->Picture= Form1->Image11->Picture; break;
                  case 11: Form1->Image30->Picture= Form1->Image3->Picture; break;
                  case 12: Form1->Image30->Picture= Form1->Image15->Picture; break;
                  }
               break;
      case 11: Form1->Image4->Width= 65;
               Form1->Image4->Height= 65;
               Form1->Image39->Picture->LoadFromFile ("Runa 4.bmp");
               Form1->Image29->Picture= Form1->Image4->Picture;
               Form1->Label2->Caption= "Plasma 4";
               Form1->Label18->Caption= "Plasma de Quetzacoatl";
               Form1->Image57->Picture->LoadFromFile("Segundo.bmp");
               switch (Tono){
                  case 0: Form1->Image30->Picture= Form1->Image8->Picture; break;
                  case 1: Form1->Image30->Picture= Form1->Image4->Picture; break;
                  case 2: Form1->Image30->Picture= Form1->Image16->Picture; break;
                  case 3: Form1->Image30->Picture= Form1->Image8->Picture; break;
                  case 4: Form1->Image30->Picture= Form1->Image20->Picture; break;
                  case 5: Form1->Image30->Picture= Form1->Image12->Picture; break;
                  case 6: Form1->Image30->Picture= Form1->Image4->Picture; break;
                  case 7: Form1->Image30->Picture= Form1->Image16->Picture; break;
                  case 8: Form1->Image30->Picture= Form1->Image8->Picture; break;
                  case 9: Form1->Image30->Picture= Form1->Image20->Picture; break;
                  case 10: Form1->Image30->Picture= Form1->Image12->Picture; break;
                  case 11: Form1->Image30->Picture= Form1->Image4->Picture; break;
                  case 12: Form1->Image30->Picture= Form1->Image16->Picture; break;
                  }
               break;
      case 12: Form1->Image5->Width= 65;
               Form1->Image5->Height= 65;
               Form1->Image39->Picture->LoadFromFile ("Runa 5.bmp");
               Form1->Image29->Picture= Form1->Image5->Picture;
               Form1->Label2->Caption= "Plasma 5";
               Form1->Label18->Caption= "Plasma de San Juan de Patmos";
               Form1->Image57->Picture->LoadFromFile("Quinto.bmp");
               switch (Tono){
                  case 0: Form1->Image30->Picture= Form1->Image9->Picture; break;
                  case 1: Form1->Image30->Picture= Form1->Image5->Picture; break;
                  case 2: Form1->Image30->Picture= Form1->Image17->Picture; break;
                  case 3: Form1->Image30->Picture= Form1->Image9->Picture; break;
                  case 4: Form1->Image30->Picture= Form1->Image21->Picture; break;
                  case 5: Form1->Image30->Picture= Form1->Image13->Picture; break;
                  case 6: Form1->Image30->Picture= Form1->Image5->Picture; break;
                  case 7: Form1->Image30->Picture= Form1->Image17->Picture; break;
                  case 8: Form1->Image30->Picture= Form1->Image9->Picture; break;
                  case 9: Form1->Image30->Picture= Form1->Image21->Picture; break;
                  case 10: Form1->Image30->Picture= Form1->Image13->Picture; break;
                  case 11: Form1->Image30->Picture= Form1->Image5->Picture; break;
                  case 12: Form1->Image30->Picture= Form1->Image17->Picture; break;
                  }
               break;
      case 13: Form1->Image6->Width= 65;
               Form1->Image6->Height= 65;
               Form1->Image29->Picture= Form1->Image6->Picture;
               Form1->Image39->Picture->LoadFromFile ("Runa 6.bmp");
               Form1->Label2->Caption= "Plasma 6";
               Form1->Label18->Caption= "Plasma de Padma Sambhava";
               Form1->Image57->Picture->LoadFromFile("Tercer.bmp");
               switch (Tono){
                  case 0: Form1->Image30->Picture= Form1->Image10->Picture; break;
                  case 1: Form1->Image30->Picture= Form1->Image6->Picture; break;
                  case 2: Form1->Image30->Picture= Form1->Image18->Picture; break;
                  case 3: Form1->Image30->Picture= Form1->Image10->Picture; break;
                  case 4: Form1->Image30->Picture= Form1->Image22->Picture; break;
                  case 5: Form1->Image30->Picture= Form1->Image14->Picture; break;
                  case 6: Form1->Image30->Picture= Form1->Image6->Picture; break;
                  case 7: Form1->Image30->Picture= Form1->Image18->Picture; break;
                  case 8: Form1->Image30->Picture= Form1->Image10->Picture; break;
                  case 9: Form1->Image30->Picture= Form1->Image22->Picture; break;
                  case 10: Form1->Image30->Picture= Form1->Image14->Picture; break;
                  case 11: Form1->Image30->Picture= Form1->Image6->Picture; break;
                  case 12: Form1->Image30->Picture= Form1->Image18->Picture; break;
                  }
               break;
      case 14: Form1->Image7->Width= 65;
               Form1->Image7->Height= 65;
               Form1->Image29->Picture= Form1->Image7->Picture;
               Form1->Image39->Picture->LoadFromFile("nada.bmp") ;
               Form1->Label2->Caption= "Plasma 7";
               Form1->Label18->Caption= "Plasma de Buda";
               Form1->Image57->Picture->LoadFromFile("Cuarto.bmp");
               switch (Tono){
                  case 0: Form1->Image30->Picture= Form1->Image11->Picture; break;
                  case 1: Form1->Image30->Picture= Form1->Image7->Picture; break;
                  case 2: Form1->Image30->Picture= Form1->Image19->Picture; break;
                  case 3: Form1->Image30->Picture= Form1->Image11->Picture; break;
                  case 4: Form1->Image30->Picture= Form1->Image23->Picture; break;
                  case 5: Form1->Image30->Picture= Form1->Image15->Picture; break;
                  case 6: Form1->Image30->Picture= Form1->Image7->Picture; break;
                  case 7: Form1->Image30->Picture= Form1->Image19->Picture; break;
                  case 8: Form1->Image30->Picture= Form1->Image11->Picture; break;
                  case 9: Form1->Image30->Picture= Form1->Image23->Picture; break;
                  case 10: Form1->Image30->Picture= Form1->Image15->Picture; break;
                  case 11: Form1->Image30->Picture= Form1->Image7->Picture; break;
                  case 12: Form1->Image30->Picture= Form1->Image19->Picture; break;
                  }
               break;
      case 15: Form1->Image8->Width= 65;
               Form1->Image8->Height= 65;
               Form1->Image29->Picture= Form1->Image8->Picture;
               Form1->Image39->Picture->LoadFromFile ("Runa 8.bmp");
               Form1->Label2->Caption= "Plasma 8";
               Form1->Label18->Caption= "Plasma de Cristo";
               Form1->Image57->Picture->LoadFromFile("Septimo.bmp");
                switch (Tono){
                  case 0: Form1->Image30->Picture= Form1->Image12->Picture; break;
                  case 1: Form1->Image30->Picture= Form1->Image8->Picture; break;
                  case 2: Form1->Image30->Picture= Form1->Image20->Picture; break;
                  case 3: Form1->Image30->Picture= Form1->Image12->Picture; break;
                  case 4: Form1->Image30->Picture= Form1->Image24->Picture; break;
                  case 5: Form1->Image30->Picture= Form1->Image16->Picture; break;
                  case 6: Form1->Image30->Picture= Form1->Image8->Picture; break;
                  case 7: Form1->Image30->Picture= Form1->Image20->Picture; break;
                  case 8: Form1->Image30->Picture= Form1->Image12->Picture; break;
                  case 9: Form1->Image30->Picture= Form1->Image24->Picture; break;
                  case 10: Form1->Image30->Picture= Form1->Image16->Picture; break;
                  case 11: Form1->Image30->Picture= Form1->Image8->Picture; break;
                  case 12: Form1->Image30->Picture= Form1->Image20->Picture; break;
                  }
                 break;
      case 16: Form1->Image9->Width= 65;
               Form1->Image9->Height= 65;
               Form1->Image29->Picture= Form1->Image9->Picture;
               Form1->Image39->Picture->LoadFromFile ("Runa 9.bmp");
               Form1->Label2->Caption= "Plasma 9";
               Form1->Label18->Caption= "Plasma de Mahoma";
               Form1->Image57->Picture->LoadFromFile("Primero.bmp");
                switch (Tono){
                  case 0: Form1->Image30->Picture= Form1->Image13->Picture; break;
                  case 1: Form1->Image30->Picture= Form1->Image9->Picture; break;
                  case 2: Form1->Image30->Picture= Form1->Image21->Picture; break;
                  case 3: Form1->Image30->Picture= Form1->Image13->Picture; break;
                  case 4: Form1->Image30->Picture= Form1->Image25->Picture; break;
                  case 5: Form1->Image30->Picture= Form1->Image17->Picture; break;
                  case 6: Form1->Image30->Picture= Form1->Image9->Picture; break;
                  case 7: Form1->Image30->Picture= Form1->Image21->Picture; break;
                  case 8: Form1->Image30->Picture= Form1->Image13->Picture; break;
                  case 9: Form1->Image30->Picture= Form1->Image25->Picture; break;
                  case 10: Form1->Image30->Picture= Form1->Image17->Picture; break;
                  case 11: Form1->Image30->Picture= Form1->Image9->Picture; break;
                  case 12: Form1->Image30->Picture= Form1->Image1->Picture; break;
                  }
               break;
      case 17: Form1->Image10->Width= 65;
               Form1->Image10->Height= 65;
               Form1->Image39->Picture->LoadFromFile ("Runa 10.bmp");
               Form1->Image29->Picture= Form1->Image10->Picture;
               Form1->Label2->Caption= "Plasma 10";
               Form1->Label18->Caption= "Plasma de Pacal Votan";
               Form1->Image57->Picture->LoadFromFile("Sexto.bmp");
                switch (Tono){
                  case 0: Form1->Image30->Picture= Form1->Image14->Picture; break;
                  case 1: Form1->Image30->Picture= Form1->Image10->Picture; break;
                  case 2: Form1->Image30->Picture= Form1->Image22->Picture; break;
                  case 3: Form1->Image30->Picture= Form1->Image14->Picture; break;
                  case 4: Form1->Image30->Picture= Form1->Image26->Picture; break;
                  case 5: Form1->Image30->Picture= Form1->Image18->Picture; break;
                  case 6: Form1->Image30->Picture= Form1->Image10->Picture; break;
                  case 7: Form1->Image30->Picture= Form1->Image22->Picture; break;
                  case 8: Form1->Image30->Picture= Form1->Image14->Picture; break;
                  case 9: Form1->Image30->Picture= Form1->Image26->Picture; break;
                  case 10: Form1->Image30->Picture= Form1->Image18->Picture; break;
                  case 11: Form1->Image30->Picture= Form1->Image10->Picture; break;
                  case 12: Form1->Image30->Picture= Form1->Image2->Picture; break;
                  }
               break;
      case 18: Form1->Image11->Width= 65;
               Form1->Image11->Height= 65;
               Form1->Image39->Picture->LoadFromFile ("Runa 11.bmp");
               Form1->Image29->Picture= Form1->Image11->Picture;
               Form1->Label2->Caption= "Plasma 11";
               Form1->Label18->Caption= "Plasma de Quetzacoatl";
               Form1->Image57->Picture->LoadFromFile("Segundo.bmp");
               switch (Tono){
                  case 0: Form1->Image30->Picture= Form1->Image15->Picture; break;
                  case 1: Form1->Image30->Picture= Form1->Image11->Picture; break;
                  case 2: Form1->Image30->Picture= Form1->Image23->Picture; break;
                  case 3: Form1->Image30->Picture= Form1->Image15->Picture; break;
                  case 4: Form1->Image30->Picture= Form1->Image27->Picture; break;
                  case 5: Form1->Image30->Picture= Form1->Image19->Picture; break;
                  case 6: Form1->Image30->Picture= Form1->Image11->Picture; break;
                  case 7: Form1->Image30->Picture= Form1->Image23->Picture; break;
                  case 8: Form1->Image30->Picture= Form1->Image15->Picture; break;
                  case 9: Form1->Image30->Picture= Form1->Image27->Picture; break;
                  case 10: Form1->Image30->Picture= Form1->Image19->Picture; break;
                  case 11: Form1->Image30->Picture= Form1->Image11->Picture; break;
                  case 12: Form1->Image30->Picture= Form1->Image3->Picture; break;
                  }
               break;
      case 19: Form1->Image12->Width= 65;
               Form1->Image12->Height= 65;
               Form1->Image29->Picture= Form1->Image12->Picture;
               Form1->Image39->Picture->LoadFromFile ("Runa 12.bmp");
               Form1->Label2->Caption= "Plasma 12";
               Form1->Label18->Caption= "Plasma de San Juan de Patmos";
               Form1->Image57->Picture->LoadFromFile("Quinto.bmp");
               switch (Tono){
                  case 0: Form1->Image30->Picture= Form1->Image16->Picture; break;
                  case 1: Form1->Image30->Picture= Form1->Image12->Picture; break;
                  case 2: Form1->Image30->Picture= Form1->Image24->Picture; break;
                  case 3: Form1->Image30->Picture= Form1->Image16->Picture; break;
                  case 4: Form1->Image30->Picture= Form1->Image28->Picture; break;
                  case 5: Form1->Image30->Picture= Form1->Image20->Picture; break;
                  case 6: Form1->Image30->Picture= Form1->Image12->Picture; break;
                  case 7: Form1->Image30->Picture= Form1->Image24->Picture; break;
                  case 8: Form1->Image30->Picture= Form1->Image16->Picture; break;
                  case 9: Form1->Image30->Picture= Form1->Image28->Picture; break;
                  case 10: Form1->Image30->Picture= Form1->Image20->Picture; break;
                  case 11: Form1->Image30->Picture= Form1->Image12->Picture; break;
                  case 12: Form1->Image30->Picture= Form1->Image4->Picture; break;
                  }
               break;
      case 20: Form1->Image13->Width= 65;
               Form1->Image13->Height= 65;
               Form1->Image29->Picture= Form1->Image13->Picture;
               Form1->Image39->Picture->LoadFromFile ("Runa 13.bmp");
               Form1->Label2->Caption= "Plasma 13";
               Form1->Label18->Caption= "Plasma de Padma Sambhava";
               Form1->Image57->Picture->LoadFromFile("Tercer.bmp");
               switch (Tono){
                  case 0: Form1->Image30->Picture= Form1->Image17->Picture; break;
                  case 1: Form1->Image30->Picture= Form1->Image13->Picture; break;
                  case 2: Form1->Image30->Picture= Form1->Image25->Picture; break;
                  case 3: Form1->Image30->Picture= Form1->Image17->Picture; break;
                  case 4: Form1->Image30->Picture= Form1->Image9->Picture; break;
                  case 5: Form1->Image30->Picture= Form1->Image21->Picture; break;
                  case 6: Form1->Image30->Picture= Form1->Image13->Picture; break;
                  case 7: Form1->Image30->Picture= Form1->Image25->Picture; break;
                  case 8: Form1->Image30->Picture= Form1->Image17->Picture; break;
                  case 9: Form1->Image30->Picture= Form1->Image9->Picture; break;
                  case 10: Form1->Image30->Picture= Form1->Image21->Picture; break;
                  case 11: Form1->Image30->Picture= Form1->Image13->Picture; break;
                  case 12: Form1->Image30->Picture= Form1->Image5->Picture; break;
                  }
               break;
      case 21: Form1->Image14->Width= 65;
               Form1->Image14->Height= 65;
               Form1->Image39->Picture->LoadFromFile("nada.bmp") ;
               Form1->Image29->Picture= Form1->Image14->Picture;
               Form1->Label2->Caption= "Plasma 14";
               Form1->Label18->Caption= "Plasma de Buda";
               Form1->Image57->Picture->LoadFromFile("Cuarto.bmp");
               switch (Tono){
                  case 0: Form1->Image30->Picture= Form1->Image18->Picture; break;
                  case 1: Form1->Image30->Picture= Form1->Image14->Picture; break;
                  case 2: Form1->Image30->Picture= Form1->Image26->Picture; break;
                  case 3: Form1->Image30->Picture= Form1->Image18->Picture; break;
                  case 4: Form1->Image30->Picture= Form1->Image10->Picture; break;
                  case 5: Form1->Image30->Picture= Form1->Image22->Picture; break;
                  case 6: Form1->Image30->Picture= Form1->Image14->Picture; break;
                  case 7: Form1->Image30->Picture= Form1->Image26->Picture; break;
                  case 8: Form1->Image30->Picture= Form1->Image18->Picture; break;
                  case 9: Form1->Image30->Picture= Form1->Image10->Picture; break;
                  case 10: Form1->Image30->Picture= Form1->Image22->Picture; break;
                  case 11: Form1->Image30->Picture= Form1->Image14->Picture; break;
                  case 12: Form1->Image30->Picture= Form1->Image6->Picture; break;
                  }
               break;
      case 22: Form1->Image15->Width= 65;
               Form1->Image15->Height= 65;
               Form1->Image29->Picture= Form1->Image15->Picture;
               Form1->Image39->Picture->LoadFromFile ("Runa 15.bmp");
               Form1->Label2->Caption= "Plasma 15";
               Form1->Label18->Caption= "Plasma de Cristo";
               Form1->Image57->Picture->LoadFromFile("Septimo.bmp");
               switch (Tono){
                  case 0: Form1->Image30->Picture= Form1->Image19->Picture; break;
                  case 1: Form1->Image30->Picture= Form1->Image15->Picture; break;
                  case 2: Form1->Image30->Picture= Form1->Image27->Picture; break;
                  case 3: Form1->Image30->Picture= Form1->Image19->Picture; break;
                  case 4: Form1->Image30->Picture= Form1->Image11->Picture; break;
                  case 5: Form1->Image30->Picture= Form1->Image23->Picture; break;
                  case 6: Form1->Image30->Picture= Form1->Image15->Picture; break;
                  case 7: Form1->Image30->Picture= Form1->Image27->Picture; break;
                  case 8: Form1->Image30->Picture= Form1->Image19->Picture; break;
                  case 9: Form1->Image30->Picture= Form1->Image11->Picture; break;
                  case 10: Form1->Image30->Picture= Form1->Image23->Picture; break;
                  case 11: Form1->Image30->Picture= Form1->Image15->Picture; break;
                  case 12: Form1->Image30->Picture= Form1->Image7->Picture; break;
                  }
               break;
      case 23: Form1->Image16->Width= 65;
               Form1->Image16->Height= 65;
               Form1->Image39->Picture->LoadFromFile ("Runa 16.bmp");
               Form1->Image29->Picture= Form1->Image16->Picture;
               Form1->Label2->Caption= "Plasma 16";
               Form1->Label18->Caption= "Plasma de Mahoma";
               Form1->Image57->Picture->LoadFromFile("Primero.bmp");
               switch (Tono){
                  case 0: Form1->Image30->Picture= Form1->Image20->Picture; break;
                  case 1: Form1->Image30->Picture= Form1->Image16->Picture; break;
                  case 2: Form1->Image30->Picture= Form1->Image28->Picture; break;
                  case 3: Form1->Image30->Picture= Form1->Image20->Picture; break;
                  case 4: Form1->Image30->Picture= Form1->Image12->Picture; break;
                  case 5: Form1->Image30->Picture= Form1->Image24->Picture; break;
                  case 6: Form1->Image30->Picture= Form1->Image16->Picture; break;
                  case 7: Form1->Image30->Picture= Form1->Image28->Picture; break;
                  case 8: Form1->Image30->Picture= Form1->Image20->Picture; break;
                  case 9: Form1->Image30->Picture= Form1->Image12->Picture; break;
                  case 10: Form1->Image30->Picture= Form1->Image24->Picture; break;
                  case 11: Form1->Image30->Picture= Form1->Image16->Picture; break;
                  case 12: Form1->Image30->Picture= Form1->Image8->Picture; break;
                  }

               break;
      case 24: Form1->Image17->Width= 65;
               Form1->Image17->Height= 65;
               Form1->Image29->Picture= Form1->Image17->Picture;
               Form1->Image39->Picture->LoadFromFile ("Runa 17.bmp");
               Form1->Label2->Caption= "Plasma 17";
               Form1->Label18->Caption= "Plasma de Pacal Votan";
               Form1->Image57->Picture->LoadFromFile("Sexto.bmp");
               switch (Tono){
                  case 0: Form1->Image30->Picture= Form1->Image21->Picture; break;
                  case 1: Form1->Image30->Picture= Form1->Image17->Picture; break;
                  case 2: Form1->Image30->Picture= Form1->Image9->Picture; break;
                  case 3: Form1->Image30->Picture= Form1->Image21->Picture; break;
                  case 4: Form1->Image30->Picture= Form1->Image13->Picture; break;
                  case 5: Form1->Image30->Picture= Form1->Image25->Picture; break;
                  case 6: Form1->Image30->Picture= Form1->Image17->Picture; break;
                  case 7: Form1->Image30->Picture= Form1->Image9->Picture; break;
                  case 8: Form1->Image30->Picture= Form1->Image21->Picture; break;
                  case 9: Form1->Image30->Picture= Form1->Image13->Picture; break;
                  case 10: Form1->Image30->Picture= Form1->Image25->Picture; break;
                  case 11: Form1->Image30->Picture= Form1->Image17->Picture; break;
                  case 12: Form1->Image30->Picture= Form1->Image9->Picture; break;
                  }
               break;
      case 25: Form1->Image18->Width= 65;
               Form1->Image18->Height= 65;
               Form1-> Image29->Picture= Form1->Image18->Picture;
               Form1->Image39->Picture->LoadFromFile ("Runa 18.bmp");
               Form1->Label2->Caption= "Plasma 18";
               Form1->Label18->Caption= "Plasma de Quetzacoatl";
               Form1->Image57->Picture->LoadFromFile("Segundo.bmp");
               switch (Tono){
                  case 0: Form1->Image30->Picture= Form1->Image22->Picture; break;
                  case 1: Form1->Image30->Picture= Form1->Image18->Picture; break;
                  case 2: Form1->Image30->Picture= Form1->Image10->Picture; break;
                  case 3: Form1->Image30->Picture= Form1->Image22->Picture; break;
                  case 4: Form1->Image30->Picture= Form1->Image14->Picture; break;
                  case 5: Form1->Image30->Picture= Form1->Image26->Picture; break;
                  case 6: Form1->Image30->Picture= Form1->Image18->Picture; break;
                  case 7: Form1->Image30->Picture= Form1->Image10->Picture; break;
                  case 8: Form1->Image30->Picture= Form1->Image22->Picture; break;
                  case 9: Form1->Image30->Picture= Form1->Image14->Picture; break;
                  case 10: Form1->Image30->Picture= Form1->Image26->Picture; break;
                  case 11: Form1->Image30->Picture= Form1->Image18->Picture; break;
                  case 12: Form1->Image30->Picture= Form1->Image10->Picture; break;
                  }
               break;
      case 26: Form1->Image19->Width= 65;
               Form1->Image19->Height= 65;
               Form1->Image29->Picture= Form1->Image19->Picture;
               Form1->Image39->Picture->LoadFromFile ("Runa 19.bmp");
               Form1->Label2->Caption= "Plasma 19";
               Form1->Label18->Caption= "Plasma de San Juan de Patmos";
               Form1->Image57->Picture->LoadFromFile("Quinto.bmp");
               switch (Tono){
                  case 0: Form1->Image30->Picture= Form1->Image23->Picture; break;
                  case 1: Form1->Image30->Picture= Form1->Image19->Picture; break;
                  case 2: Form1->Image30->Picture= Form1->Image11->Picture; break;
                  case 3: Form1->Image30->Picture= Form1->Image23->Picture; break;
                  case 4: Form1->Image30->Picture= Form1->Image15->Picture; break;
                  case 5: Form1->Image30->Picture= Form1->Image27->Picture; break;
                  case 6: Form1->Image30->Picture= Form1->Image19->Picture; break;
                  case 7: Form1->Image30->Picture= Form1->Image11->Picture; break;
                  case 8: Form1->Image30->Picture= Form1->Image23->Picture; break;
                  case 9: Form1->Image30->Picture= Form1->Image15->Picture; break;
                  case 10: Form1->Image30->Picture= Form1->Image27->Picture; break;
                  case 11: Form1->Image30->Picture= Form1->Image19->Picture; break;
                  case 12: Form1->Image30->Picture= Form1->Image11->Picture; break;
                  }
               break;
      case 27: Form1->Image20->Width= 65;
               Form1->Image20->Height= 65;
               Form1->Image29->Picture= Form1->Image20->Picture;
               Form1->Image39->Picture->LoadFromFile ("Runa 20.bmp");
               Form1->Label2->Caption= "Plasma 20";
               Form1->Label18->Caption= "Plasma de Padma Sambhava";
               Form1->Image57->Picture->LoadFromFile("Tercer.bmp");
               switch (Tono){
                  case 0: Form1->Image30->Picture= Form1->Image24->Picture; break;
                  case 1: Form1->Image30->Picture= Form1->Image20->Picture; break;
                  case 2: Form1->Image30->Picture= Form1->Image12->Picture; break;
                  case 3: Form1->Image30->Picture= Form1->Image24->Picture; break;
                  case 4: Form1->Image30->Picture= Form1->Image16->Picture; break;
                  case 5: Form1->Image30->Picture= Form1->Image28->Picture; break;
                  case 6: Form1->Image30->Picture= Form1->Image20->Picture; break;
                  case 7: Form1->Image30->Picture= Form1->Image12->Picture; break;
                  case 8: Form1->Image30->Picture= Form1->Image24->Picture; break;
                  case 9: Form1->Image30->Picture= Form1->Image16->Picture; break;
                  case 10: Form1->Image30->Picture= Form1->Image28->Picture; break;
                  case 11: Form1->Image30->Picture= Form1->Image20->Picture; break;
                  case 12: Form1->Image30->Picture= Form1->Image12->Picture; break;
                  }
               break;
      case 28: Form1->Image21->Width= 65;
               Form1->Image21->Height= 65;
               Form1->Image39->Picture->LoadFromFile("nada.bmp") ;
               Form1->Image29->Picture= Form1->Image21->Picture;
               Form1->Label2->Caption= "Plasma 21";
               Form1->Label18->Caption= "Plasma de Buda";
               Form1->Image57->Picture->LoadFromFile("Cuarto.bmp");
               switch (Tono){
                  case 0: Form1->Image30->Picture= Form1->Image25->Picture; break;
                  case 1: Form1->Image30->Picture= Form1->Image21->Picture; break;
                  case 2: Form1->Image30->Picture= Form1->Image13->Picture; break;
                  case 3: Form1->Image30->Picture= Form1->Image25->Picture; break;
                  case 4: Form1->Image30->Picture= Form1->Image17->Picture; break;
                  case 5: Form1->Image30->Picture= Form1->Image9->Picture; break;
                  case 6: Form1->Image30->Picture= Form1->Image21->Picture; break;
                  case 7: Form1->Image30->Picture= Form1->Image13->Picture; break;
                  case 8: Form1->Image30->Picture= Form1->Image25->Picture; break;
                  case 9: Form1->Image30->Picture= Form1->Image17->Picture; break;
                  case 10: Form1->Image30->Picture= Form1->Image9->Picture; break;
                  case 11: Form1->Image30->Picture= Form1->Image21->Picture; break;
                  case 12: Form1->Image30->Picture= Form1->Image13->Picture; break;
                  }
               break;
      case 29: Form1->Image22->Width= 65;
               Form1->Image22->Height= 65;
               Form1->Image29->Picture= Form1->Image22->Picture;
               Form1->Image39->Picture->LoadFromFile ("Runa 22.bmp");
               Form1->Label2->Caption= "Plasma 22";
               Form1->Label18->Caption= "Plasma de Cristo";
               Form1->Image57->Picture->LoadFromFile("Septimo.bmp");
               switch (Tono){
                  case 0: Form1->Image30->Picture= Form1->Image26->Picture; break;
                  case 1: Form1->Image30->Picture= Form1->Image22->Picture; break;
                  case 2: Form1->Image30->Picture= Form1->Image14->Picture; break;
                  case 3: Form1->Image30->Picture= Form1->Image26->Picture; break;
                  case 4: Form1->Image30->Picture= Form1->Image18->Picture; break;
                  case 5: Form1->Image30->Picture= Form1->Image10->Picture; break;
                  case 6: Form1->Image30->Picture= Form1->Image22->Picture; break;
                  case 7: Form1->Image30->Picture= Form1->Image14->Picture; break;
                  case 8: Form1->Image30->Picture= Form1->Image26->Picture; break;
                  case 9: Form1->Image30->Picture= Form1->Image18->Picture; break;
                  case 10: Form1->Image30->Picture= Form1->Image10->Picture; break;
                  case 11: Form1->Image30->Picture= Form1->Image22->Picture; break;
                  case 12: Form1->Image30->Picture= Form1->Image14->Picture; break;
                  }
               break;
      case 30: Form1->Image23->Width= 65;
               Form1->Image23->Height= 65;
               Form1->Image29->Picture= Form1->Image23->Picture;
               Form1->Image39->Picture->LoadFromFile ("Runa 23.bmp");
               Form1->Label2->Caption= "Plasma 23";
               Form1->Label18->Caption= "Plasma de Mahoma";
               Form1->Image57->Picture->LoadFromFile("Primero.bmp");
               switch (Tono){
                  case 0: Form1->Image30->Picture= Form1->Image27->Picture; break;
                  case 1: Form1->Image30->Picture= Form1->Image23->Picture; break;
                  case 2: Form1->Image30->Picture= Form1->Image15->Picture; break;
                  case 3: Form1->Image30->Picture= Form1->Image27->Picture; break;
                  case 4: Form1->Image30->Picture= Form1->Image19->Picture; break;
                  case 5: Form1->Image30->Picture= Form1->Image11->Picture; break;
                  case 6: Form1->Image30->Picture= Form1->Image23->Picture; break;
                  case 7: Form1->Image30->Picture= Form1->Image15->Picture; break;
                  case 8: Form1->Image30->Picture= Form1->Image27->Picture; break;
                  case 9: Form1->Image30->Picture= Form1->Image19->Picture; break;
                  case 10: Form1->Image30->Picture= Form1->Image11->Picture; break;
                  case 11: Form1->Image30->Picture= Form1->Image23->Picture; break;
                  case 12: Form1->Image30->Picture= Form1->Image15->Picture; break;
                  }
               break;
      case 31: Form1->Image24->Width= 65;
               Form1->Image24->Height= 65;
               Form1->Image29->Picture= Form1->Image24->Picture;
               Form1->Image39->Picture->LoadFromFile ("Runa 24.bmp");
               Form1->Label2->Caption= "Plasma 24";
               Form1->Label18->Caption= "Plasma de Pacal Votan";
               Form1->Image57->Picture->LoadFromFile("Sexto.bmp");
               switch (Tono){
                  case 0: Form1->Image30->Picture= Form1->Image28->Picture; break;
                  case 1: Form1->Image30->Picture= Form1->Image24->Picture; break;
                  case 2: Form1->Image30->Picture= Form1->Image16->Picture; break;
                  case 3: Form1->Image30->Picture= Form1->Image28->Picture; break;
                  case 4: Form1->Image30->Picture= Form1->Image20->Picture; break;
                  case 5: Form1->Image30->Picture= Form1->Image12->Picture; break;
                  case 6: Form1->Image30->Picture= Form1->Image24->Picture; break;
                  case 7: Form1->Image30->Picture= Form1->Image16->Picture; break;
                  case 8: Form1->Image30->Picture= Form1->Image28->Picture; break;
                  case 9: Form1->Image30->Picture= Form1->Image20->Picture; break;
                  case 10: Form1->Image30->Picture= Form1->Image12->Picture; break;
                  case 11: Form1->Image30->Picture= Form1->Image24->Picture; break;
                  case 12: Form1->Image30->Picture= Form1->Image16->Picture; break;
                  }
               break;
      case 32: Form1->Image25->Width= 65;
               Form1->Image25->Height= 65;
               Form1->Image39->Picture->LoadFromFile ("Runa 25.bmp");
               Form1->Image29->Picture= Form1->Image25->Picture;
               Form1->Label2->Caption= "Plasma 25";
               Form1->Label18->Caption= "Plasma de Quetzacoatl";
               Form1->Image57->Picture->LoadFromFile("Segundo.bmp");
                switch (Tono){
                  case 0: Form1->Image30->Picture= Form1->Image9->Picture; break;
                  case 1: Form1->Image30->Picture= Form1->Image25->Picture; break;
                  case 2: Form1->Image30->Picture= Form1->Image17->Picture; break;
                  case 3: Form1->Image30->Picture= Form1->Image9->Picture; break;
                  case 4: Form1->Image30->Picture= Form1->Image21->Picture; break;
                  case 5: Form1->Image30->Picture= Form1->Image13->Picture; break;
                  case 6: Form1->Image30->Picture= Form1->Image25->Picture; break;
                  case 7: Form1->Image30->Picture= Form1->Image17->Picture; break;
                  case 8: Form1->Image30->Picture= Form1->Image9->Picture; break;
                  case 9: Form1->Image30->Picture= Form1->Image21->Picture; break;
                  case 10: Form1->Image30->Picture= Form1->Image13->Picture; break;
                  case 11: Form1->Image30->Picture= Form1->Image25->Picture; break;
                  case 12: Form1->Image30->Picture= Form1->Image17->Picture; break;
                  }
               break;
      case 33: Form1->Image26->Width= 65;
               Form1->Image26->Height= 65;
               Form1->Image29->Picture= Form1->Image26->Picture;
               Form1->Image39->Picture->LoadFromFile ("Runa 26.bmp");
               Form1->Label2->Caption= "Plasma 26";
               Form1->Label18->Caption= "Plasma de San Juan de Patmos";
               Form1->Image57->Picture->LoadFromFile("Quinto.bmp");
                switch (Tono){
                  case 0: Form1->Image30->Picture= Form1->Image10->Picture; break;
                  case 1: Form1->Image30->Picture= Form1->Image26->Picture; break;
                  case 2: Form1->Image30->Picture= Form1->Image18->Picture; break;
                  case 3: Form1->Image30->Picture= Form1->Image10->Picture; break;
                  case 4: Form1->Image30->Picture= Form1->Image22->Picture; break;
                  case 5: Form1->Image30->Picture= Form1->Image14->Picture; break;
                  case 6: Form1->Image30->Picture= Form1->Image26->Picture; break;
                  case 7: Form1->Image30->Picture= Form1->Image18->Picture; break;
                  case 8: Form1->Image30->Picture= Form1->Image10->Picture; break;
                  case 9: Form1->Image30->Picture= Form1->Image22->Picture; break;
                  case 10: Form1->Image30->Picture= Form1->Image14->Picture; break;
                  case 11: Form1->Image30->Picture= Form1->Image26->Picture; break;
                  case 12: Form1->Image30->Picture= Form1->Image18->Picture; break;
                  }
               break;
      case 34: Form1->Image27->Width= 65;
               Form1->Image27->Height= 65;
               Form1->Image29->Picture= Form1->Image27->Picture;
               Form1->Image39->Picture->LoadFromFile ("Runa 27.bmp");
               Form1->Label2->Caption= "Plasma 27";
               Form1->Label18->Caption= "Plasma de Padma Sambhava";
               Form1->Image57->Picture->LoadFromFile("Tercer.bmp");
               switch (Tono){
                  case 0: Form1->Image30->Picture= Form1->Image11->Picture; break;
                  case 1: Form1->Image30->Picture= Form1->Image27->Picture; break;
                  case 2: Form1->Image30->Picture= Form1->Image19->Picture; break;
                  case 3: Form1->Image30->Picture= Form1->Image11->Picture; break;
                  case 4: Form1->Image30->Picture= Form1->Image23->Picture; break;
                  case 5: Form1->Image30->Picture= Form1->Image15->Picture; break;
                  case 6: Form1->Image30->Picture= Form1->Image27->Picture; break;
                  case 7: Form1->Image30->Picture= Form1->Image19->Picture; break;
                  case 8: Form1->Image30->Picture= Form1->Image11->Picture; break;
                  case 9: Form1->Image30->Picture= Form1->Image23->Picture; break;
                  case 10: Form1->Image30->Picture= Form1->Image15->Picture; break;
                  case 11: Form1->Image30->Picture= Form1->Image27->Picture; break;
                  case 12: Form1->Image30->Picture= Form1->Image19->Picture; break;
                  }
               break;
      case 35: Form1->Image28->Width= 65;
               Form1->Image28->Height= 65;
               Form1->Image39->Picture->LoadFromFile("nada.bmp") ;
               Form1->Image29->Picture= Form1->Image28->Picture;
               Form1->Label2->Caption= "Plasma 28";
               Form1->Label18->Caption= "Plasma de Buda";
               Form1->Image57->Picture->LoadFromFile("Cuarto.bmp");
               switch (Tono){
                  case 0: Form1->Image30->Picture= Form1->Image12->Picture; break;
                  case 1: Form1->Image30->Picture= Form1->Image28->Picture; break;
                  case 2: Form1->Image30->Picture= Form1->Image20->Picture; break;
                  case 3: Form1->Image30->Picture= Form1->Image12->Picture; break;
                  case 4: Form1->Image30->Picture= Form1->Image24->Picture; break;
                  case 5: Form1->Image30->Picture= Form1->Image16->Picture; break;
                  case 6: Form1->Image30->Picture= Form1->Image28->Picture; break;
                  case 7: Form1->Image30->Picture= Form1->Image20->Picture; break;
                  case 8: Form1->Image30->Picture= Form1->Image12->Picture; break;
                  case 9: Form1->Image30->Picture= Form1->Image24->Picture; break;
                  case 10: Form1->Image30->Picture= Form1->Image16->Picture; break;
                  case 11: Form1->Image30->Picture= Form1->Image28->Picture; break;
                  case 12: Form1->Image30->Picture= Form1->Image20->Picture; break;
                  }
               break;

     }
s+=Form1->ComboBox2->ItemIndex*4;
//Saco el Tono
switch (Tono)
       {
         case 1: Form1->Label15->Caption= "Magnetica";
                 Form1->Image31->Picture->LoadFromFile("Kin 1.bmp");
                 Form1->Memo1->Lines->Text = "TONO MAGNÉTICO - ¿Cuál es mi propósito?." ;
                 break;
         case 2: Form1->Label15->Caption= "Lunar";
                 Form1->Image31->Picture->LoadFromFile("Kin 2.bmp");
                 Form1->Memo1->Lines->Text= "TONO LUNAR - ¿ Cuál es mi desafío?.";
                 break;
         case 3: Form1->Label15->Caption= "Elélctrica";
                 Form1->Image31->Picture->LoadFromFile("Kin 3.bmp");
                 Form1->Memo1->Lines->Text= "TONO ELÉCTRICO - ¿ Cómo puedo dar un mejor servicio?.";
                  break;
         case 4: Form1->Label15->Caption= "Autoexistente";
                 Form1->Image31->Picture->LoadFromFile("Kin 4.bmp");
                 Form1->Memo1->Lines->Text= "TONO AUTO-EXISTENTE - ¿Cuál es la forma que me sincroniza?.";
                 break;
         case 5: Form1->Label15->Caption= "Entonado";
                 Form1->Image31->Picture->LoadFromFile("Kin 5.bmp");
                 Form1->Memo1->Lines->Text= "TONO ENTONADO - ¿ Cómo puedo mejorar mi autoridad?.";
                 break;
         case 6: Form1->Label15->Caption= "Rítmica";
                 Form1->Image31->Picture->LoadFromFile("Kin 6.bmp");
                 Form1->Memo1->Lines->Text= "TONO RÍTMICO - ¿ Cómo puedo organizar para equilibrar?.";
                 break;
         case 7: Form1->Label15->Caption= "Resonante";
                 Form1->Image31->Picture->LoadFromFile("Kin 7.bmp");
                 Form1->Memo1->Lines->Text="TONO RESONANTE - ¿ Cómo puedo armonizar mi servicio para con los demás?.";
                 break;
         case 8: Form1->Label15->Caption= "Galáctica";
                 Form1->Image31->Picture->LoadFromFile("Kin 8.bmp");
                 Form1->Memo1->Lines->Text="TONO GALÁCTICO - ¿Vivo lo que creo?.";
                 break;
         case 9: Form1->Label15->Caption= "Solar";
                 Form1->Image31->Picture->LoadFromFile("Kin 9.bmp");
                 Form1->Memo1->Lines->Text="TONO SOLAR - ¿Cómo logro mi propósito?.";
                 break;
         case 10: Form1->Label15->Caption= "Planetario";
                 Form1->Image31->Picture->LoadFromFile("Kin 10.bmp");
                 Form1->Memo1->Lines->Text="TONO PLANETARIO - ¿Cómo puedo perfeccionar lo que hago?.";
                 break;
         case 11: Form1->Label15->Caption= "Espectral";
                 Form1->Image31->Picture->LoadFromFile("Kin 11.bmp");
                 Form1->Memo1->Lines->Text="TONO ESPECTRAL - ¿Cómo puedo liberarme y permitirme ir?.";
                 break;
         case 12: Form1->Label15->Caption= "Cristal";
                 Form1->Image31->Picture->LoadFromFile("Kin 12.bmp");
                 Form1->Memo1->Lines->Text="TONO CRISTAL - ¿Cómo puedo dedicar mi ser a todo lo que posee vida?.";
                 break;
         case 0: Form1->Label15->Caption= "Cósmica";
                 Form1->Image31->Picture->LoadFromFile("Kin 13.bmp");
                 Form1->Memo1->Lines->Text="TONO CÓSMICO - ¿Cómo puedo expandir mi alegría y amor?.";
                 break;
                 }
//saco el nombre del Sello y escribo en el memo
switch ( Kin - (INT(Kin / 20) *20) ) {

         case 0: Form1->Label1->Caption= "Sol Amarillo";
                 Form1->Memo1->Lines->Add("* Ve con alegría hacia todo lo que te trae bienaventuranza y éxtasis.");
                 Form1->Memo1->Lines->Add("  Perdona, libera, ama a todos los seres, a toda la creación.");
                 Form1->Memo1->Lines->Add("  Ten confianza en el lenguaje de la luz dentro de tus sentimientos, es el compás espiritual que te guiará de vuelta a casa.");
                 Form1->Memo1->Lines->Add("  Abre tu corazón, goza del amor incondicional.");
                 Form1->Memo1->Lines->Add("  En todos tus pensamientos y actos irradia la presencia “Yo Soy”.");
                 break;
         case 1: Form1->Label1->Caption= "Dragon Rojo";
                 Form1->Memo1->Lines->Add("* Este signo te llama para ir a tus profundidades primordiales, en busca de la fuente abundante de la vida misma, en busca de la intuición que necesitas y añoras.");
                 Form1->Memo1->Lines->Add("  Debes ser receptivo y tener confianza.");
                 Form1->Memo1->Lines->Add("  Todo el Universo está lleno de amor.");
                 Form1->Memo1->Lines->Add("  Dar y recibir es el mensaje.");
                 Form1->Memo1->Lines->Add("  Ten CONFIANZA PRIMORDIAL y significa elegir momento a momento qué hacer, sin garantías, no intentar controlar los resultados de tu vida.");
                 Form1->Memo1->Lines->Add("  Ten fe en el guía de tu corazón, deja que te dirija.");
                 Form1->Memo1->Lines->Add("  Ten confianza en los procesos de transformación que están obrando en tu vida y evolución.");
                 break;
         case 2: Form1->Label1->Caption= "Viento Blanco";
                 Form1->Memo1->Lines->Add("* Debes abrir tu espíritu para ser guiado e inspirado.");
                 Form1->Memo1->Lines->Add("  Despierta a lo que no es visible.");
                 Form1->Memo1->Lines->Add("  Dentro de lo aparentemente complejo debes aflojarte, simplificando.");
                 Form1->Memo1->Lines->Add("  Muévete en la verdad.");
                 Form1->Memo1->Lines->Add("  Considera si tus elecciones vienen del espíritu o de las limitaciones de tus creencias inconscientes.");
                 Form1->Memo1->Lines->Add("  Sé espontáneo como el viento.");
                 Form1->Memo1->Lines->Add("  Muévete con las corrientes del cambio que se te ofrecen.");
                 Form1->Memo1->Lines->Add("  Abraza las fuerzas no visibles que se mueven para guiarnos, inspirarnos y ayudarnos.");
                 break;
         case 3: Form1->Label1->Caption= "Noche Azul";
                 Form1->Memo1->Lines->Add("* Debes introducirte en la oscuridad de la matriz, y ahí permanecer sentado en absoluta quietud.");
                 Form1->Memo1->Lines->Add("  El viaje interno de introspección e integración ha comenzado.");
                 Form1->Memo1->Lines->Add("  Libérate de manera que puedas mirar en forma plena tu actual situación desde una mirada subjetiva.");
                 Form1->Memo1->Lines->Add("  Con la NOCHE recibes dones por introducirte en tu interior, al lugar donde reside tu potencial, donde los sueños, ideas y posibilidades existen.");
                 Form1->Memo1->Lines->Add("  Aprende a utilizar tus sueños, todo lo que eres, lo que tú crees y tienes esperanza de, crea tu campo personal de ensueños.");
                 break;
         case 4: Form1->Label1->Caption= "Semilla Amarillo";
                 Form1->Memo1->Lines->Add("* Debes ahora plantar la semilla de alguna intención, proyecto o sueño.");
                 Form1->Memo1->Lines->Add("  La energía de la semilla te pide receptividad, pues la semilla germina en un campo de entrega.");
                 Form1->Memo1->Lines->Add("  No esperes las condiciones perfectas para plantar tus semillas, ahora es la temporada, tú eres la tierra receptiva, tus deseos atraerán en forma natural el apoyo que necesites.");
                 Form1->Memo1->Lines->Add("  Todos tus sueños y deseos yacen dentro de ti esperando ser despertados.");
                 break;
         case 5: Form1->Label1->Caption= "Serpiente Roja";
                 Form1->Memo1->Lines->Add("* Es la fuerza vital que te anima intuitivamente en cada instante.");
                 Form1->Memo1->Lines->Add("  Sigue las intuiciones y lo que te dice tu cuerpo.");
                 Form1->Memo1->Lines->Add("  Que tus sentidos te den las soluciones a tu problema.");
                 Form1->Memo1->Lines->Add("  Escucha lo que dice tu cuerpo, ese templo de sabiduría, crea una relación con tu cuerpo que te liberará de la atadura de viejos patrones.");
                 Form1->Memo1->Lines->Add("  La serpiente te convoca a que despiertes tu vitalidad, la sabiduría del cuerpo y la pasión por la vida.");
                 break;
         case 6: Form1->Label1->Caption= "Enlazador de mundo";
                 Form1->Memo1->Lines->Add("* Atiende el llamado de la entrega y la dejar ir las cosas.");
                 Form1->Memo1->Lines->Add("  La entrega es lo opuesto al abandono, es liberarte del deseo de querer controlar las cosas, y dejar tus ideas de lo que tú piensas deben ser.");
                 Form1->Memo1->Lines->Add("  La entrega es liberarse, todo está como tiene que ser.");
                 Form1->Memo1->Lines->Add("  Aferrarse a pasados esquemas y quejas, solo limita las posibilidades.");
                 Form1->Memo1->Lines->Add("  Perdónate y perdona a los demás.");
                 Form1->Memo1->Lines->Add("  Deja ir las cosas. Entrega lo que te limita.");
                 Form1->Memo1->Lines->Add("  Sabe que está siendo consolado y apoyado en el abrazo del amor incondicional.");
                 break;
         case 7: Form1->Label1->Caption= "Mano Azul";
                 Form1->Memo1->Lines->Add("* Mano te ofrece un portón, puedes pasar por él.");
                 Form1->Memo1->Lines->Add("  Abrete a esta oportunidad.");
                 Form1->Memo1->Lines->Add("  Examina lo que hay en tu vida que debe completarse.");
                 Form1->Memo1->Lines->Add("  Dentro de esa realización hay un natural fluir hacia lo nuevo.");
                 Form1->Memo1->Lines->Add("  Observa las realizaciones y nuevos portones por donde pasar que se están presentando ahora.");
                 Form1->Memo1->Lines->Add("  Es la apertura a recibir herramientas espirituales, talentos y dones especiales.");
                 Form1->Memo1->Lines->Add("  Abrete plenamente, estate atento a la aparición de este portal de iniciación, pero sin apegarte demasiado a libros, cartas astrológicas, tarot, es más importante la conexión divina.");
                 break;
         case 8: Form1->Label1->Caption= "Estrella Amarilla";
                 Form1->Memo1->Lines->Add("* Da un salto hacia una manera diferente de ver las cosas, de escucharlas, de ser...");
                 Form1->Memo1->Lines->Add("  Practica la armonía en tu vida diaria, que te conduce a la esencia de la estrella.");
                 Form1->Memo1->Lines->Add("  Usa la intuición, sigue lo que te indica tu corazón, deja ir las situaciones que aparentan limitar tu armonía.");
                 Form1->Memo1->Lines->Add("  Depende de ti que integres las enseñanzas para poder tener tu propio camino.");
                 break;
         case 9: Form1->Label1->Caption= "Luna Roja";
                 Form1->Memo1->Lines->Add("* Eres hijo de las estrella, semilla de estrellas, se te ofrecen dones para que recuerdes tu magnificencia, quién eres, por qué viniste, cuál es tu tarea.");
                 Form1->Memo1->Lines->Add("  Mira  tu alrededor, presta atención a lo que te atrae y te repele fuertemente.");
                 Form1->Memo1->Lines->Add("  Contempla tu inherente fuerza y talento.");
                 Form1->Memo1->Lines->Add("  El recordar te da acceso a la presencia divina, el reconocer tu conexión a un esquema mayor de la divinidad.");
                 Form1->Memo1->Lines->Add("  Está alerta a los símbolos y sueños, sensaciones que te pueden dar una respuesta a tus problemas actuales.");
                 Form1->Memo1->Lines->Add("  Atrae tu plena percepción y atención activada hacia el aquí y ahora.");
                 break;
         case 10: Form1->Label1->Caption= "Perro Blanco";
                  Form1->Memo1->Lines->Add("* Los compañeros del destino se te van acercando, que saben cómo eres en verdad.");
                  Form1->Memo1->Lines->Add("  Estate atento a la afinidad que sientes y te guía a reconocer quiénes son tus compañeros.");
                  Form1->Memo1->Lines->Add("  Siente despertar en ti el recuerdo de aquellos que se acercan para servir contigo, deja ir la idea de separación.");
                  Form1->Memo1->Lines->Add("  También examina las relaciones que tengas con amigos y compañeros que ya están en tu vida.");
                  Form1->Memo1->Lines->Add("  Si has atraído a alguien para que comparta tu vida, qué dones y enseñanzas te trae, qué pueden crear en el camino que transiten juntos.");
                  break;
         case 11: Form1->Label1->Caption= "Mono Azul";
                  Form1->Memo1->Lines->Add("* Rompe las estructuras, imágenes y creencias que ya no te sirven.");
                  Form1->Memo1->Lines->Add("  El Mono te invita a proceder de forma espontánea e impredecible.");
                  Form1->Memo1->Lines->Add("  Sonríe, no estés tan serio, cree en la magia del momento.");
                  Form1->Memo1->Lines->Add("  Observa lo que se libera con la espontaneidad, lo chistoso puede entrar en tu vida y darte vuelta todas cosas.");
                  Form1->Memo1->Lines->Add("  A medida que caen tus murallas se revela tu sonrisa y la luz de tu Esencia se hace ver.");
                  Form1->Memo1->Lines->Add("  Explora tu creatividad en lugar de pensar racionalmente, si está en una situación difícil haz lugar para el humor.");
                  break;
         case 12: Form1->Label1->Caption= "Humano Galactico";
                  Form1->Memo1->Lines->Add("* Abrete como cáliz receptor, tus circuitos están siendo preparados para la transformación a través de la activación de los dones del espíritu.");
                  Form1->Memo1->Lines->Add("  Afloja la marcha, sé receptivo y no esperes con ansiedad, aún en tiempos difíciles abre tu corazón para recibir.");
                  Form1->Memo1->Lines->Add("  Barre tu programación, tus horarios y barre bien tu mente.");
                  Form1->Memo1->Lines->Add("  Prepárate para recibir y ser activado por la fuerza y el poder, y así llegar a ser un humano plenamente potenciado.");
                  break;
         case 13: Form1->Label1->Caption= "Caminante del Cielo Rojo";
                  Form1->Memo1->Lines->Add("* Te indica que estés atento en la manera en que te relacionas y ves al mundo, los puntos de referencia están cambiando, estate atento a las oportunidades y aperturas.");
                  Form1->Memo1->Lines->Add("  Ten coraje de tomar los riesgos.");
                  Form1->Memo1->Lines->Add("  Los bordes de tu crecimiento son los que contienen la magia más grande, al explorarlos desarrollas la compasión y la comprensión por los demás que, como tú, están usando la Tierra para vivenciar un crecimiento y evolución.");
                  break;
         case 14: Form1->Label1->Caption= "Mago Blanco";
                  Form1->Memo1->Lines->Add("* Te dice que tienes la magia andando a tu alrededor, expande tu visión para abarcar aún más la magia en tu vida, de desafía a que tomes tu varita de sabiduría y hagas un uso benéfico de tu voluntad.");
                  Form1->Memo1->Lines->Add("  Te dice también que busques por dentro y no por fuera tus respuestas, a través del corazón, guía, dirige y alinea tus intenciones.");
                  Form1->Memo1->Lines->Add("  Piensa con el corazón, Procede como si llevaras la antorcha de la luz, déjate mover y danzar en la divina inocencia como canal de la más elevada magia.");
                  Form1->Memo1->Lines->Add("  Asume tu propio poder, deja ir la sensación de aprobación y de controlar.");
                  break;
         case 15: Form1->Label1->Caption= "Águila Azul";
                  Form1->Memo1->Lines->Add("* Este signo significa que traes la esperanza de poder realizar tus más preciados sueños.");
                  Form1->Memo1->Lines->Add("  Te trae también la energía de poder creer en ti mismo, en tus sueños y visiones, no importando cómo lo ven los demás.");
                  Form1->Memo1->Lines->Add("  Sé todo lo que eres.");
                  Form1->Memo1->Lines->Add("  En tu visión tienes compasión por los otros, y tus decisiones están formadas a la luz de la conciencia global.");
                  Form1->Memo1->Lines->Add("  Explora lo que te trae alegría y satisfacción, ten esperanza, cree en ti mismo, cree en tu visión.");
                  break;
         case 16: Form1->Label1->Caption= "Guerrero Amarillo";
                  Form1->Memo1->Lines->Add("* Pregúntate qué es lo que verdaderamente deseas en este momento, están en busca de la raíz de la verdad, luego reclama la natural habilidad que tienes de comunicarte con la conciencia cósmica.");
                  Form1->Memo1->Lines->Add("  Quizás puedes estar dudando de tu conexión con tu voz interna, ten confianza, tú sabes cuando algo te suena cierto, reclama tu derecho a ser guiado momento a momento, ten confianza en lo que sientes, en las señales divinas.");
                  break;
         case 17: Form1->Label1->Caption= "Tierra Roja";
                  Form1->Memo1->Lines->Add("* Este signo indica que se debe centra la percepción en el centro de uno mismo.");
                  Form1->Memo1->Lines->Add("  Los dones de la Tierra te están siendo disponibles.");
                  Form1->Memo1->Lines->Add("  Céntrate en este momento y abrirás la puerta de la sabiduría, los tiempos y las habilidades.");
                  Form1->Memo1->Lines->Add("  Echa raíces donde ahora te hallas para recibir los dones en el momento actual.");
                  Form1->Memo1->Lines->Add("  Estate atento a las sincronicidades y fuertes sensaciones, como claves de un propósito más grande.");
                  break;
         case 18: Form1->Label1->Caption= "Espejo Blanco";
                  Form1->Memo1->Lines->Add("* Te ofrece la oportunidad de verte reflejado allí y ver esa parte tuya que has estado esquivando o no has visto claramente, contempla esa parte que no reconoces, la ilusión de los problemas, esta es tu oportunidad de ver la verdad, de contemplar lo que falta.");
                  Form1->Memo1->Lines->Add("  Se te proporciona el don de la percepción.");
                  Form1->Memo1->Lines->Add("  Mira en tu espejo de la vida y poda lo que no es nada claro");
                  break;
         case 19: Form1->Label1->Caption= "Tormenta Azul";
                  Form1->Memo1->Lines->Add("* Anuncia un tiempo de profunda activación y transformación.");
                  Form1->Memo1->Lines->Add("  Estás en el cruce del camino, en medio de una revolución personal, despojándote de viejos esquemas, experiencias pasadas, enjuiciamientos, memorias y expectativas.");
                  Form1->Memo1->Lines->Add("  Se está purificando y activando tu cuerpo de luz para el renacimiento.");
                  Form1->Memo1->Lines->Add("  Los sentimientos internos que tengas son en verdad la “nafta” que te movilizará y te hará atravesar la tormenta, son el acceso a tu potencial y poder oculto.");
                  break;
                 }
//coloco el Vinal
switch ((INT(((s-1)*7 + (d-1))/20))){
 case 0: Form1->Image43->Picture->LoadFromFile("Vinal1.bmp");
            Form1->Memo1->Lines->Add("* VINAL POP: Aquel que Sabe.");
            break;
 case 1: Form1->Image43->Picture->LoadFromFile("Vinal2.bmp");
            Form1->Memo1->Lines->Add("* VINAL UO: Escucha en Silencio");
            break;
 case 2: Form1->Image43->Picture->LoadFromFile("Vinal3.bmp");
            Form1->Memo1->Lines->Add("* VINAL ZIP: Con el Fin de Integrar el Universo.");
            break;
 case 3: Form1->Image43->Picture->LoadFromFile("Vinal4.bmp");
            Form1->Memo1->Lines->Add("* VINAL ZOTZ: Basado en el Conocimiento.");
            break;
 case 4: Form1->Image43->Picture->LoadFromFile("Vinal5.bmp");
            Form1->Memo1->Lines->Add("* VINAL TZEC: Que Alacanza los Fundamentos.");
            break;
 case 5: Form1->Image43->Picture->LoadFromFile("Vinal6.bmp");
            Form1->Memo1->Lines->Add("* VINAL XUL: Donde con Gran Sabiduría una Semilla es Sembrada.");
            break;
 case 6: Form1->Image43->Picture->LoadFromFile("Vinal7.bmp");
            Form1->Memo1->Lines->Add("* VINAL YAXKIN: Un Pequeño Rayo de Sol Oculto.");
           break;
 case 7: Form1->Image43->Picture->LoadFromFile("Vinal8.bmp");
            Form1->Memo1->Lines->Add("* VINAL MOL: El cual Unifica todas las Cosas");
            break;
 case 8: Form1->Image43->Picture->LoadFromFile("Vinal9.bmp");
            Form1->Memo1->Lines->Add("* VINAL CH'EN: Para entrar en la fuente de la sabiduría interna.");
            break;
case 9: Form1->Image43->Picture->LoadFromFile("Vinal10.bmp");
            Form1->Memo1->Lines->Add("* VINAL YAX: Donde el Aprendiz Clarifica la Mente Tomando Consciencia de lo que aún no está Maduro.");
            break;
case 10: Form1->Image43->Picture->LoadFromFile("Vinal11.bmp");
            Form1->Memo1->Lines->Add("* VINAL SAC: Disipando las Nubes de la Duda, Elevandote a Ti Mismo.");
            break;
case 11: Form1->Image43->Picture->LoadFromFile("Vinal12.bmp");
            Form1->Memo1->Lines->Add("* VINAL CEH: Quiebra con la Cautela Habitual y Alcanza la Luz Blanca.");
            break;
case 12: Form1->Image43->Picture->LoadFromFile("Vinal13.bmp");
            Form1->Memo1->Lines->Add("* VINAL MAC: Cerrando el Lugar Equivocado y Entrando en Éxtasis.");
            break;
case 13: Form1->Image43->Picture->LoadFromFile("Vinal14.bmp");
            Form1->Memo1->Lines->Add("* VINAL KANKING: Recibe la luz del que sabe.");
            break;
case 14: Form1->Image43->Picture->LoadFromFile("Vinal15.bmp");
            Form1->Memo1->Lines->Add("* VINAL MOAN: Con el Fín de Ver en la Oscuridad.");
            break;
case 15: Form1->Image43->Picture->LoadFromFile("Vinal16.bmp");
            Form1->Memo1->Lines->Add("* VINAL PAX: Tocando una Música del Futuro.");
            break;
case 16: Form1->Image43->Picture->LoadFromFile("Vinal17.bmp");
            Form1->Memo1->Lines->Add("* VINAL KAYAB: Con la Canción y el Ritmo.");
            break;
case 17: Form1->Image43->Picture->LoadFromFile("Vinal18.bmp");
            Form1->Memo1->Lines->Add("* VINAL CUMHU: Situado en el Lugar Correcto donde el Alimento de la Adivinación se Obtiene.");
            break;
default : Form1->Image43->Picture->LoadFromFile("Dia25.bmp");
          Form1->Memo1->Lines->Add("* UAYEB: Es todo lo Necesario para Obtener la Piedra Preciosa.");
          Form1->Label21->Caption="-";
          break;
         }
Form1->Label21->Caption=StrToInt (INT(((s-1)*7 + (d-1))/20) + 1) ;
//Crear la onda
Onda=(Kin - (INT(Kin / 20) *20)) - (Kin - (INT( (Kin -1) / 13) *13)) + 21;
if (Onda < 0) Onda +=20;
if (Onda >=20) Onda-=20;
TS *S;
S= new TS;
Form1->Image44->Picture->LoadFromFile (S->Sello(Onda));
Form1->Image45->Picture->LoadFromFile (S->Sello(Onda + 1));
Form1->Image46->Picture->LoadFromFile (S->Sello(Onda + 2));
Form1->Image47->Picture->LoadFromFile (S->Sello(Onda + 3));
Form1->Image48->Picture->LoadFromFile (S->Sello(Onda + 4));
Form1->Image49->Picture->LoadFromFile (S->Sello(Onda + 5));
Form1->Image50->Picture->LoadFromFile (S->Sello(Onda + 6));
Form1->Image51->Picture->LoadFromFile (S->Sello(Onda + 7));
Form1->Image52->Picture->LoadFromFile (S->Sello(Onda + 8));
Form1->Image53->Picture->LoadFromFile (S->Sello(Onda + 9));
Form1->Image54->Picture->LoadFromFile (S->Sello(Onda + 10));
Form1->Image55->Picture->LoadFromFile (S->Sello(Onda + 11));
Form1->Image56->Picture->LoadFromFile (S->Sello(Onda + 12));
delete S;


//I Ching
switch (s)  {

case 1: Form1->Image41->Picture->LoadFromFile("ching17.bmp");
                break;
case 2: Form1->Image41->Picture->LoadFromFile("ching45.bmp");
                break;
case 3: Form1->Image41->Picture->LoadFromFile("ching47.bmp");
                break;
case 4: Form1->Image41->Picture->LoadFromFile("ching28.bmp");
                break;
case 5: Form1->Image41->Picture->LoadFromFile("ching48.bmp");
                break;
case 6: Form1->Image41->Picture->LoadFromFile("ching46.bmp");
                break;
case 7: Form1->Image41->Picture->LoadFromFile("ching18.bmp");
                break;
case 8: Form1->Image41->Picture->LoadFromFile("ching26.bmp");
                break;
case 9: Form1->Image41->Picture->LoadFromFile("ching22.bmp");
                break;
case 10: Form1->Image41->Picture->LoadFromFile("ching27.bmp");
                break;
case 11: Form1->Image41->Picture->LoadFromFile("ching21.bmp");
                break;
case 12: Form1->Image41->Picture->LoadFromFile("ching25.bmp");
                break;
case 13: Form1->Image41->Picture->LoadFromFile("ching17.bmp");
                break;
case 14: Form1->Image41->Picture->LoadFromFile("ching25.bmp");
                break;
case 15: Form1->Image41->Picture->LoadFromFile("ching12.bmp");
                break;
case 16: Form1->Image41->Picture->LoadFromFile("ching6.bmp");
                break;
case 17: Form1->Image41->Picture->LoadFromFile("ching44.bmp");
                break;
case 18: Form1->Image41->Picture->LoadFromFile("ching57.bmp");
                break;
case 19: Form1->Image41->Picture->LoadFromFile("ching18.bmp");
                break;
case 20: Form1->Image41->Picture->LoadFromFile("ching46.bmp");
                break;
case 21: Form1->Image41->Picture->LoadFromFile("ching11.bmp");
                break;
case 22: Form1->Image41->Picture->LoadFromFile("ching36.bmp");
                break;
case 23: Form1->Image41->Picture->LoadFromFile("ching24.bmp");
                break;
case 24: Form1->Image41->Picture->LoadFromFile("ching51.bmp");
                break;
case 25: Form1->Image41->Picture->LoadFromFile("ching17.bmp");
                break;
case 26: Form1->Image41->Picture->LoadFromFile("ching25.bmp");
                break;
case 27: Form1->Image41->Picture->LoadFromFile("ching33.bmp");
                break;
case 28: Form1->Image41->Picture->LoadFromFile("ching13.bmp");
                break;
case 29: Form1->Image41->Picture->LoadFromFile("ching1.bmp");
                break;
case 30: Form1->Image41->Picture->LoadFromFile("ching10.bmp");
                break;
case 31: Form1->Image41->Picture->LoadFromFile("ching61.bmp");
                break;
case 32: Form1->Image41->Picture->LoadFromFile("ching41.bmp");
                break;
case 33: Form1->Image41->Picture->LoadFromFile("ching19.bmp");
                break;
case 34: Form1->Image41->Picture->LoadFromFile("ching7.bmp");
                break;
case 35: Form1->Image41->Picture->LoadFromFile("ching2.bmp");
                break;
case 36: Form1->Image41->Picture->LoadFromFile("ching15.bmp");
                break;
case 37: Form1->Image41->Picture->LoadFromFile("ching62.bmp");
                break;
case 38: Form1->Image41->Picture->LoadFromFile("ching31.bmp");
                break;
case 39: Form1->Image41->Picture->LoadFromFile("ching33.bmp");
                break;
case 40: Form1->Image41->Picture->LoadFromFile("ching41.bmp");
                break;
case 41: Form1->Image41->Picture->LoadFromFile("ching4.bmp");
                break;
case 42: Form1->Image41->Picture->LoadFromFile("ching23.bmp");
                break;
case 43: Form1->Image41->Picture->LoadFromFile("ching52.bmp");
                break;
case 44: Form1->Image41->Picture->LoadFromFile("ching56.bmp");
                break;
case 45: Form1->Image41->Picture->LoadFromFile("ching33.bmp");
                break;
case 46: Form1->Image41->Picture->LoadFromFile("ching31.bmp");
                break;
case 47: Form1->Image41->Picture->LoadFromFile("ching49.bmp");
                break;
case 48: Form1->Image41->Picture->LoadFromFile("ching43.bmp");
                break;
case 49: Form1->Image41->Picture->LoadFromFile("ching58.bmp");
                break;
case 50: Form1->Image41->Picture->LoadFromFile("ching60.bmp");
                break;
case 51: Form1->Image41->Picture->LoadFromFile("ching19.bmp");
                break;
case 52: Form1->Image41->Picture->LoadFromFile("ching41.bmp");
                break;
                   }
}
 //---------------------------------------------------------------------------
#pragma package(smart_init)
